sudo: required

services:
  - docker

language: groovy

jdk:
  - oraclejdk8

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      gradle jar;
      docker login -e="$DE" -u="$DU" -p="$DP";
      docker build -t "sn0w/shiro:$TRAVIS_COMMIT" .;
      docker push sn0w/shiro;
    fi
