sudo: required

services:
  - docker

language: groovy

jdk:
  - oraclejdk8

after_success:
    - gradle jar;
      docker login -u="$DU" -p="$DP";
      docker build -t "sn0w/shiro:$TRAVIS_COMMIT" .;
      docker push "sn0w/shiro:$TRAVIS_COMMIT";
