/*!40101 SET @OLD_CHARACTER_SET_CLIENT = @@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0 */;
/*!40101 SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO' */;

CREATE DATABASE IF NOT EXISTS `shiro` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `shiro`;

CREATE TABLE IF NOT EXISTS `core` (
  `key`   VARCHAR(250) NOT NULL,
  `value` TEXT,
  PRIMARY KEY (`key`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS `music` (
  `hash`      VARCHAR(250) NOT NULL,
  `title`     VARCHAR(100) DEFAULT NULL,
  `source`    VARCHAR(500) DEFAULT NULL,
  `extractor` VARCHAR(100) DEFAULT NULL,
  `user`      VARCHAR(100) DEFAULT NULL,
  `channel`   VARCHAR(100) DEFAULT NULL,
  `guild`     VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (`hash`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS `prefixes` (
  `key`   VARCHAR(250) NOT NULL,
  `value` TEXT,
  PRIMARY KEY (`key`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS `ratings` (
  `id`    INT(11)      NOT NULL AUTO_INCREMENT,
  `user`  VARCHAR(100) NOT NULL,
  `guild` VARCHAR(100) NOT NULL,
  `score` INT(11)      NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS `reminders` (
  `id`        INT(11)      NOT NULL AUTO_INCREMENT,
  `sent`      TINYINT(1)   NOT NULL DEFAULT '0',
  `timestamp` VARCHAR(250) NOT NULL,
  `guild`     VARCHAR(250) NOT NULL,
  `channel`   VARCHAR(250) NOT NULL,
  `user`      VARCHAR(250) NOT NULL,
  `message`   VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

/*!40101 SET SQL_MODE = IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS = IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT = @OLD_CHARACTER_SET_CLIENT */;
